# Generated by Django 3.2.8 on 2021-10-21 12:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0002_auto_20211020_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='money',
            field=models.DecimalField(decimal_places=3, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Money'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='trading_logic.Item'),
        ),
    ]
