# Generated by Django 3.2.8 on 2021-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0003_auto_20211021_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='currency',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='currency',
            field=models.ManyToManyField(to='trading_logic.Currency'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(to='trading_logic.Item'),
        ),
    ]
