# Generated by Django 3.2.8 on 2021-10-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0004_auto_20211021_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='trading_logic.currency'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sell'), (2, 'Buy')]),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(related_name='item', to='trading_logic.Item'),
        ),
    ]
