# Generated by Django 3.2.8 on 2021-10-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0005_auto_20211025_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='item',
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='trading_logic.Item'),
        ),
    ]
