# Generated by Django 3.2.8 on 2021-10-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0007_rename_item_watchlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(to='trading_logic.Item'),
        ),
    ]
