# Generated by Django 3.2.8 on 2021-10-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0009_auto_20211027_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stocks quantity'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='entry_quantity',
            field=models.PositiveIntegerField(verbose_name='Requested quantity'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Current quantity'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
