# Generated by Django 3.2.9 on 2021-11-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0010_auto_20211027_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='trading_logic.item'),
        ),
    ]
