# Generated by Django 3.2.9 on 2021-11-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_logic', '0011_alter_offer_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='description',
        ),
    ]
